name: Flutter Build APK (v2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter SDK (clone stable)
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Ensure Flutter project structure (create if missing)
        run: |
          if [ ! -f pubspec.yaml ] || [ ! -d android ] || [ ! -d ios ]; then
            echo "Running flutter create to ensure correct project structure..."
            flutter create -t app .
          else
            echo "Flutter project structure present."
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release --no-shrink

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
